### ISSUE TITLE
Release binary

### ISSUE THREAD

**Issue by benbalter** [benbalter/zoom-go#5]

**Comment by parkr** [comment]
Go supports cross-compilation of binaries! For now, users will have to `go get github.com/benbalter/zoom-go/...`, but eventually you can pre-build them for a handful of os and architecture combinations.

**Comment by KevinGimbel** [comment]
I would recommend [goreleaser](https://github.com/goreleaser/goreleaser). It's a superb tool for automating the building - and releasing to github - of Go binaries. 

You can see an example of how to configure it on my [license tool](https://github.com/kevingimbel/license/), for example this release page https://github.com/kevingimbel/license/releases/tag/v1.0.4 and the corresponding config file: https://github.com/kevingimbel/license/blob/v1.0.4/.goreleaser.yml 

If you want help setting goreleaser up I'd be happy to help!

**Comment by parkr** [comment]
I approve... this is great! https://goreleaser.com

**Comment by KevinGimbel** [comment]
Would you like to merge https://github.com/benbalter/zoom-go/pull/9 first?

I'd be happy to implement / setup goreleaser afterwards. Probably on Sunday or Monday if that's OK with you and if you want help with it. :)

**Comment by benbalter** [comment]
@kevingimbel Please!

**Comment by KevinGimbel** [comment]
@benbalter I have opened PR #11, feel free to ask questions or request changes as you see fit. :)

**Comment by benbalter** [comment]
Thanks to @kevingimbel amazing help, we now have https://github.com/benbalter/zoom-go/releases/tag/v0.1.0

**Comment by KevinGimbel** [comment]
Glad I could help. :)
