### ISSUE TITLE
Error: missing redirect URL in the client_credentials.json

### ISSUE THREAD

**Issue by doronbehar** [benbalter/zoom-go#96]
### Describe the bug

I get this error:

```
Importing credentials from "/home/doron/downloads/credentials.json"...
error importing credentials: oauth2/google: missing redirect URL in the client_credentials.json
github.com/benbalter/zoom-go/config.ReadGoogleClientConfigFromFile
        /var/src/zoom-go/config/config.go:51
main.importGoogleClientConfig
        /var/src/zoom-go/cmd/zoom/main.go:53
main.main
        /var/src/zoom-go/cmd/zoom/main.go:92
runtime.main
        /nix/store/dq7pgplzsdlgjy3v7yzy7sd4ym4an909-go-1.14/share/go/src/runtime/proc.go:203
runtime.goexit
        /nix/store/dq7pgplzsdlgjy3v7yzy7sd4ym4an909-go-1.14/share/go/src/runtime/asm_amd64.s:1373
```

### Steps to reproduce the behavior

1. Use latest master
2. Follow these instructions from the builtin help:

```
1. Create a new project
        1. Go to https://console.developers.google.com
        2. Switch to your work account if need be (top right)
        3. Create a new project dropdown, top left next to your domain
2. Grant the project Calendar API access
        1. Click "Enable API"
        2. Type "Calendar" in the search box
        3. Click "Calendar API"
        4. Click "Enable"
3. Grab your credentials
        1. Click "Credentials" on the left side
```

The next step (3.2) says:

```
        2. Create a new OAuth credential with type "other"
```

But as of currently, there's no such an application type available to choose in the web interface. I chose "Desktop App" and I got that error. From as far as I can see, only by choosing a "Web application" type, I can add an authorized redirect URI. Which I assume will be `http://localhost:<some port>`?

### Expected behavior

- The builtin instructions will instruct to use a "Web application" application type and instruct to add a proper redirect URI.
- In case the json file doesn't include the proper keys, a better error message will be printed, indicating this is probably due to a wrong application type chosen in the console's web interface.

### Screenshots

![NUX-selection:2020 03 18-15:57:31](https://user-images.githubusercontent.com/10998835/76968230-76ba1d00-6920-11ea-9f3b-6c9d99cd6fbe.png)

### Additional context

I haven't yet managed to make this program work for me but to put my 2 cents, I'm still not sure after reading the README what's this program's purpose.

**Comment by doronbehar** [comment]
UPDATE:

I've tested `-import` with the URI: `http://localhost` and I get now the error:

```
error importing credentials: open /home/doron/.config/google/client_secrets.json: no such file or directory
github.com/benbalter/zoom-go/config.(*FileProvider).StoreGoogleClientConfig
        /var/src/zoom-go/config/file.go:79
main.importGoogleClientConfig
        /var/src/zoom-go/cmd/zoom/main.go:61
main.main
        /var/src/zoom-go/cmd/zoom/main.go:95
runtime.main
        /nix/store/dq7pgplzsdlgjy3v7yzy7sd4ym4an909-go-1.14/share/go/src/runtime/proc.go:203
runtime.goexit
        /nix/store/dq7pgplzsdlgjy3v7yzy7sd4ym4an909-go-1.14/share/go/src/runtime/asm_amd64.s:1373
```

Apparently,`~/.config/google/` is not created automatically, needed to be created by hand.

zoom-go opened my browser and all that, I authorized my app and I was redirected to `https://localhost/...`. After that, I guessed I need to grab what's after `code=` for this:

```
Your browser is about to open. When it does, please authorize the application when prompted and paste the token it gives you below.
Authorization token: 
```

That worked I think, but then since I have no zoom meetings, I got the error message:

```
error fetching next meetings: no zoom events upcoming
github.com/benbalter/zoom-go.NextEvents
        /var/src/zoom-go/zoom.go:53
main.main
        /var/src/zoom-go/cmd/zoom/main.go:119
runtime.main
        /nix/store/dq7pgplzsdlgjy3v7yzy7sd4ym4an909-go-1.14/share/go/src/runtime/proc.go:203
runtime.goexit
        /nix/store/dq7pgplzsdlgjy3v7yzy7sd4ym4an909-go-1.14/share/go/src/runtime/asm_amd64.s:1373
```

I assume by now `zoom-go` is not capable of openning zoom links from a URL?

**Comment by parkr** [comment]
> I assume by now `zoom-go` is not capable of openning zoom links from a URL?

How, exactly, are your meetings specifying the URL? Also, what does the URL look like?

**Comment by parkr** [comment]
This PR will fix reading `zoom.us` URL's _without_ a subdomain: https://github.com/benbalter/zoom-go/pull/98.

**Comment by parkr** [comment]
This PR will fix `~/.config/google/` not being created when you import: https://github.com/benbalter/zoom-go/pull/99

**Comment by parkr** [comment]
> I assume by now `zoom-go` is not capable of openning zoom links from a URL?

`zoom-go` will read your calendar and pull Zoom URL's from your calendar. If you pass it a Zoom URL as an argument, it will ignore it and read from your calendar.

**Comment by parkr** [comment]
With #98 & #99 merged, I'm going to close this!
